export const HAS_DONE_TODO = 'HAS_DONE_TODO'
export const NOT_DONE_TODO = 'NOT_DONE_TODO'
export const ALL_TODO = 'ALL_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const FILTER_TODO = 'FILTER_TODO'
export const ADD_TODO = 'ADD_TODO'